// Package service — VectorStore abstraction.
//
// The Store interface lets us swap the vector backend without touching
// callers. Today we have an in-memory JSON-backed implementation
// (VectorStore in vectorstore.go). Stage 3 introduces a Qdrant adapter
// that satisfies the same interface.
//
// Design rule (from AGENTS.md / core-principles): the vector store is an
// evidence layer, not a decision layer. Filters are expressed as structured
// data, never as LLM-interpreted instructions.
package service

import (
	"context"

	"github.com/cfo/backend/internal/model"
)

// VectorFilter is a structured, pre-retrieval filter. Filtering happens
// BEFORE similarity search whenever the backend supports it (Qdrant native
// filter DSL; in-memory: linear scan with predicate). Never post-filter.
//
// Zero-valued fields mean "no constraint on this field".
type VectorFilter struct {
	// Industry narrows to a specific vertical (education/ecommerce/pharma/generic).
	Industry model.IndustryType

	// DocType narrows to "P&L", "BalanceSheet", "CashFlow", etc.
	DocType model.DocType

	// Source is an exact-match filename filter. Prefer DocumentIDs when
	// you have them; Source is only here for free-form RAG seed chunks.
	Source string

	// DocumentIDs is an allow-list of source document IDs.
	DocumentIDs []string

	// PeriodStart / PeriodEnd define a target range (YYYY-MM-DD).
	// A chunk matches if the chunk's period OVERLAPS this range.
	// Both must be set to apply — empty = no period constraint.
	PeriodStart string
	PeriodEnd   string
}

// IsZero reports whether the filter imposes any constraint.
func (f VectorFilter) IsZero() bool {
	return f.Industry == "" &&
		f.DocType == "" &&
		f.Source == "" &&
		len(f.DocumentIDs) == 0 &&
		f.PeriodStart == "" &&
		f.PeriodEnd == ""
}

// SearchQuery bundles all inputs for a vector search. Keeping this as a
// struct (not positional args) makes it cheap to add new fields (e.g.,
// MMR reranking, alpha for hybrid) without churning every call site.
type SearchQuery struct {
	// Text is the user query. It is embedded by the store.
	Text string

	// TopK caps the number of results returned.
	TopK int

	// MinScore drops results below this cosine similarity (0..1).
	// Zero means "no minimum".
	MinScore float32

	// Filter is applied BEFORE similarity search when supported.
	Filter VectorFilter
}

// Store is the abstraction every vector backend must satisfy.
// Implementations: *VectorStore (in-memory), *QdrantStore (Stage 3).
//
// All methods take a context and return errors. Implementations MUST:
//   - honor ctx cancellation
//   - be safe for concurrent calls
//   - never mutate the input slice in AddDocuments
//   - apply VectorFilter before similarity search, not after
type Store interface {
	// AddDocuments upserts chunks. Embeddings are generated by the store
	// if VectorDocument.Embedding is empty.
	AddDocuments(ctx context.Context, docs []VectorDocument) error

	// Search returns up to q.TopK results ranked by similarity.
	Search(ctx context.Context, q SearchQuery) ([]SimilarityResult, error)

	// DeleteByDocumentID removes every chunk whose DocumentID matches.
	// Returns the number of chunks removed.
	DeleteByDocumentID(ctx context.Context, documentID string) (int, error)

	// Count returns the number of chunks matching filter (zero filter = all).
	Count(ctx context.Context, filter VectorFilter) (int, error)

	// Clear removes every chunk matching filter. Zero filter = wipe.
	Clear(ctx context.Context, filter VectorFilter) (int, error)

	// Close releases resources (network connections for remote stores).
	// Safe to call multiple times.
	Close() error
}

// matchesFilter is a pure helper used by in-memory implementations to
// decide if a VectorDocument passes a VectorFilter. Qdrant translates the
// same struct into its native filter DSL instead (see qdrant_store.go).
//
// TODO: unit-test every branch in vectorstore_filter_test.go.
func matchesFilter(doc VectorDocument, f VectorFilter) bool {
	if f.Industry != "" && doc.IndustryType != f.Industry {
		return false
	}
	if f.DocType != "" && doc.DocType != f.DocType {
		return false
	}
	if f.Source != "" && doc.Source != f.Source {
		return false
	}
	if len(f.DocumentIDs) > 0 {
		found := false
		for _, id := range f.DocumentIDs {
			if doc.DocumentID == id {
				found = true
				break
			}
		}
		if !found {
			return false
		}
	}
	if f.PeriodStart != "" && f.PeriodEnd != "" {
		// Chunk has no period info → cannot match a period-scoped query.
		// This is intentional: when the user asks "Q1 2024", we must not
		// leak chunks with unknown period into the evidence set.
		if doc.PeriodStart == "" || doc.PeriodEnd == "" {
			return false
		}
		if !periodsOverlap(doc.PeriodStart, doc.PeriodEnd, f.PeriodStart, f.PeriodEnd) {
			return false
		}
	}
	return true
}

// periodsOverlap is a string-based YYYY-MM-DD overlap check. String compare
// works because the format is lexically sortable. Invalid dates are treated
// as "might overlap" (lenient), so a malformed period never silently hides
// evidence — the conflict detector catches those downstream.
func periodsOverlap(aStart, aEnd, bStart, bEnd string) bool {
	if aStart == "" || aEnd == "" || bStart == "" || bEnd == "" {
		return true
	}
	// Overlap iff !(aEnd < bStart || bEnd < aStart)
	return !(aEnd < bStart || bEnd < aStart)
}
